### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by dzulfikar68**

### CODE REVIEW

**Comment by coconutzdev** [comment]
This is not necessary. If you pull request just for merchandise in HacktoberFest event this year, please create pull request with  some good improvement, not just readme. Thanks!

**Comment by fajarainul** [comment]
This is not necessary. If you pull request just for merchandise in HacktoberFest event this year, please create pull request with some good improvement, not just readme. Thanks!

**Comment by dzulfikar68** [comment]
i see, i know what your message, but i think i will be KEPPREEEET KYEEEEEHHH CUUUUUNGGG!!!!! for you @fajarainul.

**Comment by fajarainul** [comment]
What are you talking about? What is "KEPPREEEET KYEEEEEHHH CUUUUUNGGG!!!!!" mean? Are you ok?

**Comment by dzulfikar68** [comment]
Hehh cuuung kyehhhhh!!!!!!!!???? 👋👋👋

**Pull request merged**
